[project]
name = "noga"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["matplotlib>=3.10.8", "openpyxl>=3.1.5", "pandas>=3.0.0"]

[project.scripts]
noga-stat = "noga.stat:main"
